config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "restaurants#index"

  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"

  # get "/restaurants", to: "restaurants#index"
  # get "/restaurants/:id", to: "restaurants#show"

  resources :restaurants, except: %i[edit update destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[Chinese Italian Japanese French Belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @review = Review.new
  # end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class="m-4">
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div>
<h1> All Restaurants </h1>
<% @restaurants.each do |restaurant| %>
<h3><%= link_to restaurant.name, restaurant_path(restaurant) %> - (<%= restaurant.category.capitalize %>)</h3>
<p><%= restaurant.address %></p>
<% end %>
<%= link_to "Add new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>
<%=simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :category, :collection => %w[Chinese Italian Japanese French Belgian]%>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<h4> <%= @restaurant.category.capitalize %></h4>
<p> Address: <%= @restaurant.address %> </p>
<p> Contact Us: <%= @restaurant.phone_number %>
<h3> Reviews </h3>
<% @restaurant.reviews.each do |review| %>
<div class="fw-bold"><%= review.rating %> Stars </div>
<p><%= review.content %></p>
<% end %>
<%= link_to "Back to restaurants", restaurants_path %>
<%#= link_to "Add new review", new_restaurant_review_path(@restaurant) %>
<h2>New Review</h2>
<%=simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating, :collection => [0, 1, 2, 3, 4, 5]%>
<%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%# <h2>New Review</h2> %>
<%#=simple_form_for [@restaurant, @review] do |f| %>
<%#= f.input :content %>
<%#= f.input :rating, :collection => [0, 1, 2, 3, 4, 5]%>
<%#= f.submit %>
<%# end %>